name: API Automation Test Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup gradlew
      run: chmod +x gradlew

    - name: build gradle
      run: ./gradlew build

    - name: Run gradle test
      run:  ./gradlew test

    - name: Allure Report HTML
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: build/allure-results

