name: API Automation Test Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Setup gradlew
      run: chmod +x gradlew

    - name: Run API Tests
      run: ./gradlew clean test -DsuiteXmlFile=testing.xml

    - name: Install Allure
      run: |
        sudo apt-add-repository ppa:qameta/allure -y
        sudo apt-get update
        sudo apt-get install allure -y

    - name: Allure Report
      run:  allure generate build/allure-results

    - name: Allure Report HTML
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: build/allure-results

